# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
os: linux
dist: xenial

before_install:
  - add-apt-repository ppa:ubuntugis/ppa --yes
  - apt-get --yes --force-yes update -qq
  # rgdal dependencies:
  - apt-get install --yes libproj-dev libgdal-dev

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - libudunits2-dev
